name: deploy-my-web-page

env:
  S3_BUKET_NAME: ozs-storage
  REGION: ca-central-1
  REPO_NAME: ${{ github.event.repository.name }}
  ENVIROMENT: my

on: 
  push:
    branches: 
      - feature/BusinessCard

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
      - name: npm run deploy
        run: npm run deploy
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}
      - name: Copy zip to S3
        run: aws s3 cp ./ s3://${{ env.S3_BUKET_NAME }}/${{ env.ENVIROMENT }}/${{ env.REPO_NAME }} --recursive  --exclude "*" --include "*.zip"
      - name: Finish CI
        run: echo "Finish CI!"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy main_page
        run: ll -la
      
#TODO
#sonarqube
#build Docker image
#check for vulnerabilities in container images
      
    
