name: deploy-my-web-page

env:
  S3_BUKET_NAME: ozs-storage
  REGION: ca-central-1

on: 
  push:
    branches: 
      - feature/BusinessCard

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
      - name: npm run deploy
        run: npm run deploy
      - name: ls -la
        run: ls -la
      - name: aws version
        run: aws --version
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}
      - name: S3 list
        run: aws s3 ls
      - name: Copy zip to S3
        run: aws s3 cp *.zip s3://${{ env.S3_BUKET_NAME }}${{ github.action_repository }}/
      - name: Finish CI
        run: echo "Finish CI!"
      
    
